version: '3'

services:
###> doctrine/doctrine-bundle ###
  nginx:
    build: .docker/nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/onesight_test
    depends_on:
      - php
      - database
    
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_onesight
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
###< doctrine/doctrine-bundle ###
  php:
    build:
      context: .docker/php
    container_name: php
    volumes:
      - .:/home/wwwroot
    depends_on:
      - database

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
